# Move the directory to the second line
format ='''
$directory$fill$git_branch $git_status
[➤](bold blue) '''
palette='funky'

[directory]
read_only=''
truncate_to_repo=false
style='bold cyan'
truncation_length=5
truncation_symbol="…/"

[git_branch]
format='[ $symbol$branch(:$remote_branch)]($style)'

[git_status]
untracked='[?$count](red)'
modified='[!$count](yellow)'
staged='[+$count](green)'
style=''
format='([$staged $modified $untracked]($style) )'

[fill]
symbol=' '

[palettes.funky]
darker_cyan='32'
